# Simple CircleCI config
# version: 2
# jobs: 
#  build:
#    docker: 
#      - image: srcml/ubuntu_x86_64_base
#    steps:
#      - checkout
#      - run: cd assignments/bigint && make tests


# One illustrating Workflows
version: 2
jobs:
  build:
    docker: 
      - image: srcml/ubuntu_x86_64_base
    steps:
      - checkout
      - run: cd assignments/bigint && make bigint.o

  test:
    docker: 
      - image: srcml/ubuntu_x86_64_base
    steps:
      - checkout
      - run: cd	assignments/bigint && make tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
