version: 2
jobs:
  build:
    docker:
      - image: srcml/ubuntu_x86_64_base
    steps:
      - checkout
      - run: cd assignments/bigint &&
          make
  test:
    docker:
      - image: srcml/ubuntu_x86_64_base
    steps:
      - checkout
      - run: echo "Ran test job" &&
          ls assignments/bigint
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
